Add Schema.Lazy to support recursive macro derivation
zio/zio-schema pull request #70
Opened 2021-06-02 22:56 UTC by thinkharderdev

Handle recursive macro derivation by wrapping case class fields in a `Schema.Lazy[A](f: () => Schema[A])`

2021-06-03 00:24 UTC, jdegoes commented on zio-schema/shared/src/main/scala/zio/schema/Schema.scala
> +  final case class Lazy[A](schema: () => Schema[A]) extends Schema[A]
```suggestion
  final case class Lazy[A](private val schema0: () => Schema[A]) extends Schema[A] {
    lazy val schema = schema0
  }
```

2021-06-03 00:44 UTC, jdegoes commented on zio-schema/shared/src/test/scala/zio/schema/DeriveSchemaSpec.scala
> +      test("correctly derives for case classes with recursive types") {
So great to see these passing! 🎉 👯‍♂️

2021-06-03 00:44 UTC, jdegoes requested changes
Just a minor comment, otherwise looks great!

2021-06-04 10:23 UTC, thinkharderdev commented on zio-schema/shared/src/main/scala/zio/schema/Schema.scala
> +  final case class Lazy[A](schema: () => Schema[A]) extends Schema[A]
Good call!

2021-06-04 10:30 UTC, thinkharderdev commented on zio-schema/shared/src/main/scala/zio/schema/Schema.scala
> +  final case class Lazy[A](schema: () => Schema[A]) extends Schema[A]
Done!

2021-06-05 18:31 UTC, jdegoes approved these changes

2021-06-05 18:32 UTC, jdegoes commented
Fantastic work on this. Thank you! 🙏

2021-06-05 18:40 UTC, merged

2021-06-05 19:26 UTC, jdegoes commented
@thinkharderdev Looks like docs failed, can you take a look?

<https://github.com/zio/zio-schema/actions/runs/909896564>

2021-06-06 18:59 UTC, thinkharderdev commented
> @thinkharderdev Looks like docs failed, can you take a look?
> 
> https://github.com/zio/zio-schema/actions/runs/909896564

Should be fixed with my PR. Never added a website to this repo.